### ISSUE TITLE
Antlr Tool fails on Ada2005Parser.g4

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/antlr-ng#17]
grammar: [Ada2005Lexer.g4](https://github.com/antlr/grammars-v4/blob/7f917add1199e8b050a7117814899ebab50a3c3b/ada/ada2005/Ada2005Lexer.g4) [Ada2005Parser.g4](https://github.com/antlr/grammars-v4/blob/7f917add1199e8b050a7117814899ebab50a3c3b/ada/ada2005/Ada2005Parser.g4)

antlr-ng version: https://github.com/mike-lischke/antlr-ng/commit/e9423bbd9c83a8f2581be1e84282075c32a59483

Output:
```
ken@DESKTOP-DL44R7B:~/antlr-ng$ node --no-warnings --loader ts-node/esm cli/runner.ts -Dlanguage=TypeScript   $w/Ada2005Parser.g4
file:///home/ken/antlr-ng/src/codegen/model/Action.ts:62
            __runInitializers(this, _chunks_extraInitializers);
            ^

ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new Action (file:///home/ken/antlr-ng/src/codegen/model/Action.ts:62:13)
    at ParserFactory.action (file:///home/ken/antlr-ng/src/codegen/ParserFactory.ts:72:17)
    at OutputModelController.action (file:///home/ken/antlr-ng/src/codegen/OutputModelController.ts:350:33)
    at SourceGenTriggers.element (file:///home/ken/antlr-ng/src/tree-walkers/SourceGenTriggers.ts:501:48)
    at SourceGenTriggers.alt (file:///home/ken/antlr-ng/src/tree-walkers/SourceGenTriggers.ts:300:57)
    at SourceGenTriggers.alternative (file:///home/ken/antlr-ng/src/tree-walkers/SourceGenTriggers.ts:221:26)
    at SourceGenTriggers.block (file:///home/ken/antlr-ng/src/tree-walkers/SourceGenTriggers.ts:168:53)
    at SourceGenTriggers.subrule (file:///home/ken/antlr-ng/src/tree-walkers/SourceGenTriggers.ts:863:40)
    at SourceGenTriggers.element (file:///home/ken/antlr-ng/src/tree-walkers/SourceGenTriggers.ts:492:41)
    at SourceGenTriggers.alt (file:///home/ken/antlr-ng/src/tree-walkers/SourceGenTriggers.ts:300:57)

Node.js v23.5.0
ken@DESKTOP-DL44R7B:~/antlr-ng$
```

The tool works fine generating the lexer for the lexer grammar, which is done first. It fails for the second (Parser) grammar.

**Comment by mike-lischke** [comment]
I cannot reproduce this problem with the latest code. Both C++ and TypeScript parsers are generated as expected.

**Comment by mike-lischke** [comment]
Ah, I know the reason for this failure: ts-node. When you use tsx instead it should run fine.

**Comment by kaby76** [comment]
Works fine with latest.
